### ISSUE TITLE
Attribute routing

### ISSUE THREAD

**Issue by waynebrantley** [ivaylokenov/ASP.NET-MVC-Lambda-Expression-Helpers#12]
Is this supposed to work with attribute routing?
added ``[RouteArea]`` at the top of HomeController (not passing anything so it would be the root page).
added ``[Route("somepage"]`` to a somepage action on the controller.
Used your library to generate a url to ``HomeController.SomePage()`` and it generated ``Home\SomePage`` instead of ``\SomePage``

So, I was not sure if this just generated default routes or was supposed to also use attribute routing?

**Comment by ivaylokenov** [comment]
@waynebrantley The library just extracts the names of the expression values and uses the original methods from the MVC library.

I noticed something strange going on in the generation of URLs.

Consider this action:
```c#
[RouteArea]
public class HomeController : Controller
{
    [Route("SomeAction")]
    public ActionResult Index()
    {
        return Content($"{Url.Action("Index", "Home")} - {Url.Action<HomeController>(c => c.Index())}");
    }
```

Returns /SomeAction - /
It is because the expression provides an empty string for the "area" route value, if no area is present. If it didn't, it would fail on correct area generation.

And if you change the route area to an empty string like so:

```c#
[RouteArea("")]
public class HomeController : Controller
{
    [Route("SomeAction")]
    public ActionResult Index()
    {
        return Content($"{Url.Action("Index", "Home")} - {Url.Action<HomeController>(c => c.Index())}");
    }
```

Then the result is correct - /SomeAction - /SomeAction

The only solution here is to check explicitly for the RouteArea attribute and extract its value.

**Comment by waynebrantley** [comment]
That is odd, I will watch for other odd behaviors.  Thanks for looking/finding (and fixing at some point)

**Comment by ivaylokenov** [comment]
@waynebrantley I will update the library in less than an hour. Stay tuned!

**Comment by ivaylokenov** [comment]
@waynebrantley Package is now updated on NuGet.
